name: Docs

on:
  push:
    branches:
      - master

jobs:
  github-actions:
    strategy:
      matrix:
        node-version: [16.x]
        os:
          - name: Ubuntu
            version: ubuntu-latest
    name: Node.js ${{ matrix.node-version }} - ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Redoc CLI
        run: yarn global add redoc-cli
      - name: Build Docs
        run: redoc-cli build ./services/server/docs/swagger.json --output ./services/server/docs/index.html --title "Chess API"
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          clean: true
          folder: services/server/docs
          force: true
          git-config-name: hieudoanm
          git-config-email: hieumdoan@gmail.com
          single-commit: true
          silent: true
          token: ${{ secrets.GH_PAGES_TOKEN }}
